### ISSUE TITLE
apple küldi

### ISSUE THREAD

**Issue by Paradoxx88** [lordoftheflies/wonderjam#106]
Performance - 2.1

We discovered one or more bugs in your app when reviewed on iPad running iOS 10.0.2 on Wi-Fi connected to an IPv6 network.

Content was unable to load.

The steps to reproduce are:

- Launch the app
- Blank screen with black status bar displays

We've attached screenshot(s) for your reference.

Next Steps

Please run your app on a device while connected to an IPv6 network (all apps must support IPv6) to identify the issue(s), then revise and resubmit your app for review.

If we misunderstood the intended behavior of your app, please reply to this message in Resolution Center to provide information on how these features were intended to work.

For new apps, uninstall all previous versions of your app from a device, then install and follow the steps to reproduce the issue(s). For updates, install the new version as an update to the previous version, then follow the steps to reproduce the issue(s).

Resources

For information about supporting IPv6 Networks, please refer to Supporting IPv6 DNS64/NAT64 Networks and About Networking
If you have difficulty reproducing a reported issue, please try testing the workflow described in [Technical Q&A QA1764: How to reproduce bugs reported against App Store](https://developer.apple.com/library/content/qa/qa1764/_index.html) submissions.

If you have code-level questions after utilizing the above resources, you may wish to consult with Apple Developer Technical Support. When the DTS engineer follows up with you, please be ready to provide:
- complete details of your rejection issue(s)
- screenshots
- steps to reproduce the issue(s)
- symbolicated crash logs - if your issue results in a crash log

![image](https://cloud.githubusercontent.com/assets/17258860/20370458/15893b50-ac5f-11e6-82b3-0a957e817dfb.png)

**Comment by lordoftheflies** [comment]
@Paradoxx88 ezzel akkor most mi van?
